version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: stylelint
    versions:
    - 13.13.0
  - dependency-name: ts-jest
    versions:
    - 26.5.5
